-- Products Table
CREATE TABLE products (
    product_id        NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    category_id       NUMBER NOT NULL,
    supplier_id       NUMBER NOT NULL,
    product_name      VARCHAR2(100) NOT NULL,
    unit_price        NUMBER(12,2) NOT NULL,
    status            VARCHAR2(20) DEFAULT 'ACTIVE' CHECK (status IN ('ACTIVE', 'INACTIVE')),
    created_at        DATE DEFAULT SYSDATE,
    CONSTRAINT product_category_fk FOREIGN KEY (category_id) REFERENCES categories(category_id),
    CONSTRAINT product_supplier_fk FOREIGN KEY (supplier_id) REFERENCES suppliers(supplier_id)
);
/* Product details with reference to category and supplier */

-- Categories Table
CREATE TABLE categories (
    category_id   NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name          VARCHAR2(100) UNIQUE NOT NULL,
    description   VARCHAR2(255)
);

-- Warehouses Table
CREATE TABLE warehouses (
    warehouse_id  NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name          VARCHAR2(100) NOT NULL,
    location      VARCHAR2(200)
);

-- Inventory Table
CREATE TABLE inventory (
    inventory_id      NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id        NUMBER NOT NULL,
    warehouse_id      NUMBER NOT NULL,
    quantity_on_hand  NUMBER NOT NULL,
    min_stock_level   NUMBER DEFAULT 5,
    max_stock_level   NUMBER DEFAULT 500,
    reorder_point     NUMBER DEFAULT 10,
    CONSTRAINT inv_product_fk FOREIGN KEY (product_id) REFERENCES products(product_id),
    CONSTRAINT inv_warehouse_fk FOREIGN KEY (warehouse_id) REFERENCES warehouses(warehouse_id),
    CONSTRAINT inv_uniq UNIQUE (product_id, warehouse_id)
);

-- Suppliers Table
CREATE TABLE suppliers (
    supplier_id   NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name          VARCHAR2(100) NOT NULL,
    email         VARCHAR2(150),
    phone         VARCHAR2(20)
);

-- Transactions Table
CREATE TABLE transactions (
    txn_id         NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    inventory_id   NUMBER NOT NULL,
    txn_type       VARCHAR2(20) CHECK (txn_type IN ('SALE','RESTOCK','ADJUST')),
    txn_date       DATE DEFAULT SYSDATE,
    quantity       NUMBER NOT NULL,
    note           VARCHAR2(255),
    CONSTRAINT txn_inventory_fk FOREIGN KEY (inventory_id) REFERENCES inventory(inventory_id)
);

-- Error Log Table (for utilities)
CREATE TABLE error_log (
    log_id           NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    module           VARCHAR2(100),
    error_message    VARCHAR2(4000),
    error_date       DATE DEFAULT SYSDATE,
    custom_context   VARCHAR2(4000)
);
